### ISSUE TITLE
Cannot run program "youtube-dl" error=2

### ISSUE THREAD

**Issue by JoeBenyon** [sapher/youtubedl-java#2]
Hi, I am getting this error

`Cannot run program "youtube-dl" (in directory "/Users/name/Workspace/directory"): error=2, No such file or directory, com.sapher.youtubedl.YoutubeDLException: Cannot run program "youtube-dl" (in directory "/Users/name/Workspace/directory"): error=2, No such file or directory`

When I know that this directory `/Users/name/Workspace/directory` exists.

When I go to that directory and run youtube-dl manually through the terminal it works fine. Any help would be appreciated 😄

**Comment by sapher** [comment]
Sorry for the late reply. Your issue is that the program can't find the *youtubedl* executable in the following folder */Users/name/Workspace/directory*. The library look in the PATH to get the executable. For some reason it's not working for you.

I've update the library to 1.1. With that version you can manually set the path of your *youtube-dl* executable with that function `YoutubeDL.setExecutablePath("/your/path/youtube-dl")`.

You can get the full path of the exec by typing this in a terminal : `which youtube-dl`. Mine gives me `/usr/bin/youtube-dl`. So I can set manually the path with `YoutubeDL.setExecutablePath("/usr/bin/youtube-dl")`.

You can use this link for the instruction to install the new version : [youtubedl-java-1.1](https://jitpack.io/#sapher/youtubedl-java/1.1)

I hope this will help you.

**Comment by JoeBenyon** [comment]
That's great thanks
